### PR TITLE
Implement option to skip fields inside doUpdate function

### PR DESCRIPTION
**Pull request by celsomarques**

### CODE REVIEW

**Comment by Suor** [comment]
Backward incompatibility is unacceptable and has no real reason here. And `'-field'` api is questionable.

**Comment by celsomarques** [comment]
First of all, thank you for excellent job!!!

Why is there backward incompatibility? 

I've an scenario where table has 30 fields and I need to update all fields except two.
In above scenario it's very nasty to put 28 fields in array.

**Comment by Suor** [comment]
I meant not supporting `.doUpdate('age')`, I missed that it doesn't work anyway, so it's not backwards incompatibility, my bad :). This should work though.

The issues with your API are:
- column name can actually start from `-`
- this is new thing not used in sql-bricks anywhere now

The upside is simplicity. Alternative approaches which I can think of are more verbose:
```js
stmt.doUpdate(sql.except('age', 'name'))
// or
stmt.doUpdate().except('age', 'name')
``` 

I can't see why you can't solve it outside if sql-bricks-postgres though:
```js
const rec = {age: 23, name: 'Marques', ...} // many more fields
const toUpdate = _.difference(Object.keys(rec), ['field_to_exclude1', 'field2'])
sql.insert('user', rec).onConflict('name').doUpdate(toUpdate)
```

**Comment by celsomarques** [comment]
I got it!
I'll close this PR.
Thank you

**Pull request closed without merging**
